const state={boot:null,token:localStorage.getItem('km_token')||'',user:JSON.parse(localStorage.getItem('km_user')||'null'),category:'',query:'',favorites:new Set()};
const $=s=>document.querySelector(s); const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function money(n){return new Intl.NumberFormat('pt-AO',{style:'currency',currency:'AOA',maximumFractionDigits:0}).format(Number(n)||0).replace('AOA','Kz');}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.add('hidden'),3000)}
const API_BASE=(window.__KAMBA_API_BASE__||'').replace(/\/$/,'');
async function api(path,opt={}){path=API_BASE+path;opt.headers={...(opt.headers||{}),'Content-Type':'application/json'};if(state.token)opt.headers.Authorization='Bearer '+state.token;const r=await fetch(path,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erro');return d;}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
$('#closeModal').onclick=closeModal;$('.modal-backdrop').onclick=closeModal;$('#mobileMenu').onclick=()=>$('#mobileNav').classList.toggle('hidden');
function contactSeller(phone){const digits=String(phone||'').replace(/\D/g,''); if(!digits)return toast('Contacto indisponível'); window.open('https://wa.me/244'+(digits.startsWith('244')?digits.slice(3):digits),'_blank','noopener,noreferrer')}
function productCard(p){const fav=state.favorites.has(p.id);return `<article class="card clickable" onclick="productDetails('${p.id}')"><img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.title)}" loading="lazy"><div class="card-body"><div class="card-top"><span class="badge">${escapeHtml(p.categoryName||'Produto')}</span>${p.featured?'<span class="verified">🔥 Destaque</span>':''}</div><h3>${escapeHtml(p.title)}</h3><p class="muted">📍 ${escapeHtml(p.location)} • ${escapeHtml(p.condition)}</p><div class="price">${money(p.price)}</div><p class="muted">${escapeHtml(p.description).slice(0,90)}${p.description.length>90?'…':''}</p><div class="card-actions" onclick="event.stopPropagation()"><button class="btn primary" onclick="contactSeller('${escapeHtml(p.phone)}')">WhatsApp</button><button class="btn ghost" onclick="favorite('${p.id}')">${fav?'♥':'♡'} Guardar</button></div></div></article>`}
function serviceCard(s){return `<article class="card"><div class="card-body"><div class="service-icon">🧰</div><div class="card-top"><span class="badge">${escapeHtml(s.category)}</span>${s.featured?'<span class="verified">🔥 Destaque</span>':''}</div><h3>${escapeHtml(s.title)}</h3><p class="muted">📍 ${escapeHtml(s.location)}</p><div class="price">Desde ${money(s.priceFrom)}</div><p class="muted">${escapeHtml(s.description).slice(0,110)}${s.description.length>110?'…':''}</p><div class="card-actions"><button class="btn primary" onclick="contactSeller('${escapeHtml(s.phone)}')">Contactar</button><button class="btn ghost" onclick="reportItem('${s.id}')">Denunciar</button></div></div></article>`}
function render(){const b=state.boot;$('#statProducts').textContent=b.products.length;$('#statServices').textContent=b.services.length;$('#homeCategory').innerHTML='<option value="">Todas as categorias</option>'+b.categories.map(c=>`<option value="${c.id}">${c.icon} ${escapeHtml(c.name)}</option>`).join('');$('#categoryRow').innerHTML=b.categories.map(c=>`<button class="cat-chip ${state.category===c.id?'active':''}" onclick="filterCategory('${c.id}')">${c.icon} ${escapeHtml(c.name)}</button>`).join('');let ps=b.products;if(state.category)ps=ps.filter(p=>p.categoryId===state.category);if(state.query){const q=state.query.toLowerCase();ps=ps.filter(p=>(p.title+' '+p.description).toLowerCase().includes(q))}$('#productGrid').innerHTML=ps.slice(0,12).map(productCard).join('')||'<div class="empty">Nenhum anúncio encontrado.</div>';$('#serviceGrid').innerHTML=b.services.slice(0,6).map(serviceCard).join('')||'<div class="empty">Nenhum serviço disponível.</div>';$('#plansGrid').innerHTML=b.plans.map((p,i)=>`<article class="plan ${i===1?'featured':''}"><span class="badge">${escapeHtml(p.name)}</span><div class="plan-price">${p.price?money(p.price)+'/mês':'Grátis'}</div><ul>${p.features.map(x=>`<li>✓ ${escapeHtml(x)}</li>`).join('')}</ul><button class="btn ${i===1?'primary':'ghost'}" onclick="subscribe('${p.id}')">Escolher ${escapeHtml(p.name)}</button></article>`).join('');renderDashboard();}
function filterCategory(c){state.category=state.category===c?'':c;render();location.hash='market'}
async function productDetails(pid){
  let p=state.boot.products.find(x=>x.id===pid); if(!p)return;
  try { const d=await api('/api/products/'+encodeURIComponent(pid)); p=d.product; } catch(e) {}
  openModal(`<div class="product-modal"><img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.title)}"><div><span class="badge">${escapeHtml(p.categoryName)}</span><h2>${escapeHtml(p.title)}</h2><div class="price big">${money(p.price)}</div><p>${escapeHtml(p.description)}</p><p class="muted">📍 ${escapeHtml(p.location)} • ${escapeHtml(p.condition)}</p><div class="actions"><button class="btn primary" onclick="contactSeller('${escapeHtml(p.phone)}')">WhatsApp</button><button class="btn primary" onclick="buyProduct('${p.id}')">Comprar</button>${p.seller?`<button class="btn ghost" onclick="messageSeller('${p.seller.id}')">Mensagem</button>`:''}<button class="btn ghost" onclick="favorite('${p.id}');closeModal()">${state.favorites.has(p.id)?'Retirar dos favoritos':'Guardar anúncio'}</button>${p.affiliateEnabled!==false?`<button class="btn ghost" onclick="affiliateLink('${p.id}')">💰 Ganhar com este produto</button>`:''}</div></div></div>`)
}
async function favorite(pid){if(!state.token)return loginModal();try{const r=await api('/api/favorites',{method:'POST',body:JSON.stringify({productId:pid})});if(r.favorite)state.favorites.add(pid);else state.favorites.delete(pid);render();toast(r.favorite?'Adicionado aos favoritos.':'Retirado dos favoritos.')}catch(e){toast(e.message)}}
function loginModal(){openModal(`<h2>Entrar no Kamba Market</h2><p class="muted">A conta de demonstração usa <b>demo@kambamarket.ao</b> e a palavra-passe <b>12345678</b>.</p><form id="loginForm"><div class="field"><label>Telefone ou e-mail</label><input name="identifier" required autocomplete="username"></div><div class="field"><label>Palavra-passe</label><input type="password" name="password" required autocomplete="current-password"></div><button class="btn primary full">Entrar</button></form><p class="muted center-gap">Ainda não tem conta? <a href="#" id="toRegister">Criar conta</a></p>`);$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const r=await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});state.token=r.token;state.user=r.user;localStorage.setItem('km_token',state.token);localStorage.setItem('km_user',JSON.stringify(state.user));closeModal();await refreshMe();toast('Bem-vindo!');if(state.user.role==='admin')loadAdmin()}catch(err){toast(err.message)}};$('#toRegister').onclick=e=>{e.preventDefault();registerModal()}}
function registerModal(){openModal(`<h2>Criar conta</h2><form id="registerForm"><div class="form-grid"><div class="field"><label>Nome</label><input name="name" required></div><div class="field"><label>Telefone</label><input name="phone" placeholder="923000000" required></div></div><div class="field"><label>E-mail</label><input type="email" name="email"></div><div class="field"><label>Palavra-passe</label><input type="password" name="password" minlength="8" required><small>Mínimo de 8 caracteres.</small></div><button class="btn primary full">Criar conta</button></form>`);$('#registerForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast('Conta criada. Agora entre.');loginModal()}catch(err){toast(err.message)}}}
function sellModal(kind='product'){if(!state.token)return loginModal();if(kind==='service')return serviceModal();openModal(`<h2>Publicar produto</h2><p class="muted">O anúncio ficará pendente de moderação.</p><form id="sellForm"><div class="field"><label>Título</label><input name="title" required maxlength="120"></div><div class="form-grid"><div class="field"><label>Preço (Kz)</label><input type="number" min="1" name="price" required></div><div class="field"><label>Categoria</label><select name="categoryId">${state.boot.categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}</select></div></div><div class="form-grid"><div class="field"><label>Localização</label><input name="location" placeholder="Luanda"></div><div class="field"><label>Estado</label><select name="condition"><option>Novo</option><option>Usado</option><option>Recondicionado</option></select></div></div><div class="field"><label>Descrição</label><textarea rows="4" name="description"></textarea></div><div class="field"><label>URL da imagem</label><input name="image" placeholder="https://..."></div><button class="btn primary full">Publicar anúncio</button></form>`);$('#sellForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/products',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast('Anúncio enviado para moderação.');closeModal();await refreshMe()}catch(err){toast(err.message)}}}
function serviceModal(){openModal(`<h2>Oferecer serviço</h2><form id="serviceForm"><div class="field"><label>Serviço</label><input name="title" required maxlength="120"></div><div class="form-grid"><div class="field"><label>Categoria</label><input name="category" placeholder="Eletricista" required></div><div class="field"><label>Preço inicial (Kz)</label><input type="number" min="0" name="priceFrom" value="0"></div></div><div class="field"><label>Localização</label><input name="location" value="Luanda"></div><div class="field"><label>Descrição</label><textarea rows="4" name="description"></textarea></div><button class="btn primary full">Publicar serviço</button></form>`);$('#serviceForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/services',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast('Serviço enviado para moderação.');closeModal();await refreshMe()}catch(err){toast(err.message)}}}
async function renderDashboard(){
  const d=$('#dashboardContent');
  if(!state.user){
    d.innerHTML='<div class="empty"><span class="eyebrow">Conta</span><h2>Minha conta</h2><p>Entre para gerir anúncios, favoritos, serviços e subscrição.</p><button class="btn primary" onclick="loginModal()">Entrar</button></div>';
    return;
  }
  d.innerHTML=`<div class="dashboard-head"><div><span class="eyebrow">Conta</span><h2>Olá, ${escapeHtml(state.user.name)} 👋</h2><p class="muted">${escapeHtml(state.user.phone)} • ${state.user.verified?'Telefone verificado':'Verificação pendente'}</p></div><button class="btn ghost" onclick="logout()">Sair</button></div><div class="dash-grid"><div class="stat"><span class="muted">Plano</span><strong id="dashPlan">Gratuito</strong></div><div class="stat"><span class="muted">Anúncios</span><strong id="dashProducts">0</strong></div><div class="stat"><span class="muted">Favoritos</span><strong id="dashFavorites">0</strong></div><div class="stat"><span class="muted">Serviços</span><strong id="dashServices">0</strong></div></div><div class="actions"><button class="btn primary" onclick="sellModal()">+ Publicar produto</button><button class="btn ghost" onclick="sellModal('service')">+ Oferecer serviço</button><button class="btn ghost" onclick="affiliateDashboard()">💰 Afiliados</button>${state.user.role==='admin'?'<button class="btn ghost" onclick="loadAdmin()">Painel admin</button>':''}</div><div id="myProducts" class="my-list"></div>`;
  api('/api/me').then(r=>{
    const active=r.subscription?.planId;
    $('#dashPlan').textContent=state.boot.plans.find(p=>p.id===active)?.name||'Gratuito';
    $('#dashProducts').textContent=r.products.length;
    $('#dashFavorites').textContent=r.favoriteIds.length;
    $('#dashServices').textContent=r.services.length;
    state.favorites=new Set(r.favoriteIds);
    const rows=[
      ...r.products.map(p=>`<div class="admin-item"><div><b>${escapeHtml(p.title)}</b><div class="muted">Produto • ${money(p.price)} • ${p.status}</div></div></div>`),
      ...r.services.map(s=>`<div class="admin-item"><div><b>${escapeHtml(s.title)}</b><div class="muted">Serviço • Desde ${money(s.priceFrom)} • ${s.status}</div></div></div>`)
    ];
    $('#myProducts').innerHTML='<h3>Meus anúncios</h3>'+(rows.length?rows.join(''):'<p class="muted">Ainda não publicou anúncios ou serviços.</p>');
  });
}
async function refreshMe(){if(!state.token)return;try{const r=await api('/api/me');state.user=r.user;localStorage.setItem('km_user',JSON.stringify(state.user));state.favorites=new Set(r.favoriteIds||[]);renderDashboard();}catch(e){logout(true)}}
async function logout(silent=false){try{if(state.token)await api('/api/logout',{method:'POST'})}catch{} state.token='';state.user=null;state.favorites.clear();localStorage.removeItem('km_token');localStorage.removeItem('km_user');renderDashboard();if(!silent)toast('Sessão terminada.')}
async function subscribe(planId){if(!state.token)return loginModal();try{const r=await api('/api/subscribe',{method:'POST',body:JSON.stringify({planId})});toast(r.message)}catch(e){toast(e.message)}}
async function buyProduct(pid){
  if(!state.token)return loginModal();
  const p=state.boot.products.find(x=>x.id===pid); if(!p)return;
  openModal(`<h2>Comprar ${escapeHtml(p.title)}</h2><form id="buyForm"><div class="field"><label>Quantidade</label><input name="quantity" type="number" min="1" max="20" value="1" required></div><div class="field"><label>Método de pagamento</label><select name="paymentMethod"><option value="cash_delivery">Pagamento na entrega</option><option value="bank_transfer">Transferência bancária</option><option value="wallet">Carteira móvel</option></select></div><p class="muted">Na versão atual a encomenda fica pendente até a integração do gateway.</p><button class="btn primary full">Criar encomenda</button></form>`);
  $('#buyForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));b.productId=pid;b.quantity=Number(b.quantity);b.affiliateCode=localStorage.getItem('km_affiliate_code')||'';try{const r=await api('/api/orders',{method:'POST',body:JSON.stringify(b)});toast('Encomenda criada.');closeModal();renderDashboard();}catch(err){toast(err.message)}};
}
async function messageSeller(userId){if(!state.token)return loginModal();openModal(`<h2>Enviar mensagem</h2><form id="msgForm"><div class="field"><label>Mensagem</label><textarea name="text" maxlength="1000" rows="5" required placeholder="Olá, ainda está disponível?"></textarea></div><button class="btn primary full">Enviar</button></form>`);$('#msgForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/messages',{method:'POST',body:JSON.stringify({toUserId:userId,text:e.target.text.value})});toast('Mensagem enviada.');closeModal();}catch(err){toast(err.message)}}}
async function reportItem(id){if(!state.token)return loginModal();openModal(`<h2>Denunciar</h2><p class="muted">Ajude-nos a manter a plataforma segura.</p><form id="reportForm"><div class="field"><label>Motivo</label><select name="reason"><option>Fraude ou burla</option><option>Produto proibido</option><option>Informação falsa</option><option>Spam</option><option>Outro</option></select></div><button class="btn primary full">Enviar denúncia</button></form>`);$('#reportForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));try{await api('/api/reports',{method:'POST',body:JSON.stringify({targetId:id,reason:b.reason})});toast('Denúncia enviada.');closeModal()}catch(err){toast(err.message)}}}
async function affiliateLink(pid){if(!state.token)return loginModal();try{const r=await api('/api/affiliate/link',{method:'POST',body:JSON.stringify({productId:pid})});const share=r.link;try{await navigator.clipboard.writeText(share);toast('Link de afiliado copiado! Ganhe 5% nas vendas elegíveis.')}catch{openModal(`<h2>Seu link de afiliado</h2><p class="muted">Partilhe este link. Se a compra for concluída, a comissão será registada.</p><input class="small-input full" value="${escapeHtml(share)}" readonly>`)} }catch(e){toast(e.message)}}
async function affiliateDashboard(){
  if(!state.token)return loginModal();
  try{
    let r=await api('/api/affiliate/dashboard');
    if(!r.affiliate){await api('/api/affiliate/join',{method:'POST'});r=await api('/api/affiliate/dashboard')}
    const a=r.affiliate; const w=await api('/api/affiliate/wallet');
    openModal(`<h2>💰 Programa de Afiliados</h2>
    <p class="muted">Partilhe produtos do Kamba Market e receba comissão sobre vendas elegíveis.</p>
    <div class="admin-cards"><div class="admin-card"><span>Cliques</span><b>${a.clicks||0}</b></div><div class="admin-card"><span>Conversões</span><b>${a.conversions||0}</b></div><div class="admin-card"><span>Comissões ganhas</span><b>${money(a.earnings||0)}</b></div><div class="admin-card"><span>Disponível</span><b>${money(w.wallet.available)}</b></div></div>
    <p><b>Seu código:</b> ${escapeHtml(a.code)} • <b>Comissão:</b> ${Math.round((a.commissionRate||0.05)*100)}%</p>
    <h3>💳 Levantar saldo</h3><form id="withdrawForm"><div class="form-grid"><div class="field"><label>Valor (Kz)</label><input name="amount" type="number" min="5000" step="100" max="${Math.max(5000,w.wallet.available)}" required></div><div class="field"><label>Método</label><select name="method"><option value="wallet">Carteira móvel</option><option value="multicaixa_express">Multicaixa Express</option><option value="bank_transfer">Transferência bancária</option></select></div></div><div class="field"><label>Conta / número de destino</label><input name="destination" required placeholder="Ex.: 923000000"></div><button class="btn primary full" ${w.wallet.available<5000?'disabled':''}>Solicitar levantamento</button></form>
    <p class="muted">Mínimo: 5.000 Kz. O administrador deve aprovar e processar o levantamento.</p>
    <h3>🔗 Seus links</h3>${(r.links||[]).map(l=>`<div class="admin-item"><div><b>${escapeHtml(l.product)}</b><div class="muted">${l.clicks||0} cliques</div></div><button class="btn ghost" onclick="navigator.clipboard.writeText('${escapeHtml(location.origin+'/r/'+a.code+'?p='+l.productId)}');toast('Copiado!')">Copiar</button></div>`).join('')||'<p class="muted">Ainda não tem links. Abra um produto e escolha “Ganhar com este produto”.</p>'}
    <h3>📜 Levantamentos</h3>${(w.withdrawals||[]).map(x=>`<div class="admin-item"><div><b>${money(x.amount)}</b><div class="muted">${escapeHtml(x.method)} • ${escapeHtml(x.status)}</div></div><span class="muted">${new Date(x.createdAt).toLocaleDateString('pt-AO')}</span></div>`).join('')||'<p class="muted">Nenhum levantamento solicitado.</p>'}`);
    const form=$('#withdrawForm'); if(form) form.onsubmit=async e=>{e.preventDefault();try{await api('/api/affiliate/withdraw',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast('Pedido de levantamento enviado!');affiliateDashboard()}catch(err){toast(err.message)}};
  }catch(e){toast(e.message)}
}
async function loadAdmin(){
  if(!state.user||state.user.role!=='admin')return; $('#admin').classList.remove('hidden');
  try{
    const [s,p,w,o]=await Promise.all([api('/api/admin/stats'),api('/api/admin/pending'),api('/api/admin/withdrawals'),api('/api/admin/orders')]);
    $('#adminContent').innerHTML=`<div class="admin-cards"><div class="admin-card"><span>Utilizadores</span><b>${s.users}</b></div><div class="admin-card"><span>Anúncios</span><b>${s.products}</b></div><div class="admin-card"><span>Serviços</span><b>${s.services}</b></div><div class="admin-card"><span>Afiliados</span><b>${s.affiliates}</b></div><div class="admin-card"><span>Levantamentos</span><b>${w.withdrawals.filter(x=>x.status==='requested').length}</b></div></div>
    <div class="admin-list"><h3>Itens pendentes</h3>${[...p.products.map(x=>({...x,type:'product'})),...p.services.map(x=>({...x,type:'service'}))].map(x=>`<div class="admin-item"><div><b>${escapeHtml(x.title)}</b><div class="muted">${x.type==='product'?'Produto':'Serviço'} • ${escapeHtml(x.status||'pending')}</div></div><div class="actions"><button class="btn primary" onclick="moderate('${x.id}','${x.type}',true)">Aprovar</button><button class="btn ghost" onclick="moderate('${x.id}','${x.type}',false)">Rejeitar</button></div></div>`).join('')||'<p class="muted">Sem itens pendentes.</p>'}</div>
    <div class="admin-list"><h3>💳 Levantamentos de afiliados</h3>${w.withdrawals.map(x=>`<div class="admin-item"><div><b>${escapeHtml(x.user)}</b><div class="muted">${money(x.amount)} • ${escapeHtml(x.method)} • ${escapeHtml(x.destination)} • ${escapeHtml(x.status)}</div></div><div class="actions"><select onchange="updateWithdrawal('${x.id}',this.value)"><option value="">Alterar...</option><option value="approved">Aprovar</option><option value="processing">Processando</option><option value="paid">Pago</option><option value="rejected">Rejeitar</option></select></div></div>`).join('')||'<p class="muted">Sem levantamentos.</p>'}</div>
    <div class="admin-list"><h3>🛒 Encomendas</h3>${o.orders.slice(0,30).map(x=>`<div class="admin-item"><div><b>${escapeHtml(x.product)}</b><div class="muted">${escapeHtml(x.buyer)} → ${escapeHtml(x.seller)} • ${money(x.total)} • ${escapeHtml(x.status)}${x.affiliateCommission?` • comissão ${money(x.affiliateCommission)}`:''}</div></div><select onchange="updateOrder('${x.id}',this.value)"><option value="">Estado...</option><option value="paid">Pago</option><option value="completed">Concluído</option><option value="cancelled">Cancelado</option></select></div>`).join('')||'<p class="muted">Sem encomendas.</p>'}</div>`;
  }catch(e){toast(e.message)}
}
async function updateWithdrawal(id,status){if(!status)return;try{await api('/api/admin/withdrawal',{method:'POST',body:JSON.stringify({id,status})});toast('Levantamento atualizado.');loadAdmin()}catch(e){toast(e.message)}}
async function updateOrder(id,status){if(!status)return;try{await api('/api/admin/order',{method:'POST',body:JSON.stringify({id,status})});toast('Encomenda atualizada.');loadAdmin()}catch(e){toast(e.message)}}
async function moderate(id,type,approved){try{await api('/api/admin/approve',{method:'POST',body:JSON.stringify({id,type,approved})});toast(approved?'Aprovado':'Rejeitado');loadAdmin();state.boot=await api('/api/bootstrap');render()}catch(e){toast(e.message)}}
$('#loginBtn').onclick=loginModal;$('#sellBtn').onclick=()=>sellModal();$('#serviceCta').onclick=()=>sellModal('service');$('#searchBtn').onclick=()=>{state.query=$('#homeSearch').value.trim();state.category=$('#homeCategory').value;render();location.hash='market'};$('#allProductsBtn').onclick=()=>{state.query='';state.category='';$('#homeSearch').value='';$('#marketSearch').value='';render()};$('#marketSearch').oninput=e=>{state.query=e.target.value;render()};$('#homeSearch').addEventListener('keydown',e=>{if(e.key==='Enter')$('#searchBtn').click()});document.addEventListener('click',e=>{const sc=e.target.closest('[data-scroll]');if(sc)document.getElementById(sc.dataset.scroll)?.scrollIntoView({behavior:'smooth'});if(e.target.closest('.mobile-nav a'))$('#mobileNav').classList.add('hidden')});
(async()=>{try{state.boot=await api('/api/bootstrap');render();if(state.token)await refreshMe();if(state.user?.role==='admin')loadAdmin()}catch(e){toast('Falha a carregar a plataforma')}})();
